version: '3.9'

services:
  app:
    build: ../
    platform: linux/amd64
    restart: ${APP_RESTART}
    ports:
      - ${APP_PORT:-4407}:${APP_PORT:-4407}
    environment:
      APP_NAME: "${APP_NAME}"
      APP_PORT: "${APP_PORT}"
      DB_NAME: "${DB_NAME}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_LOCAL_HOST:-${DB_HOST}}"
      DB_PORT: "${DB_LOCAL_PORT:-${DB_PORT}}"
      PCLOUD_OAUTH_CLIENT_ID: "${PCLOUD_OAUTH_CLIENT_ID}"
      PCLOUD_OAUTH_CALLBACK_URL: "${PCLOUD_OAUTH_CALLBACK_URL}"
    networks:
      - server

  db:
    image: mysql:8.0-oracle
    restart: ${APP_RESTART}
    ports:
      - ${DB_PORT:-4407}:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    networks:
      - server

networks:
  server:

volumes:
  db: